name: SonarQube Scan

on:
  push:
    branches:
      - merge_requests
      - master
      - develop
  workflow_dispatch:

env:
  SONAR_HOST_URL: <SONARQUBE_URL>
  SONAR_TOKEN: <SONARQUBE_TOKEN>

jobs:
  scan-cli:
    name: SonarQube Scan for CLI
    runs-on: sonarsource/sonar-scanner-cli:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apk add --update --no-cache python3 py3-pip
          sudo pip install sonar-tools
          sudo apk add curl
          sudo apk add coreutils

      - name: Build and Analyze with SonarScanner CLI
        run: |
          cd comp-cli
          sonar-scanner -Dsonar.qualitygate.wait=true -X
          cd -
