jobs:
  scan-maven:
    name: SonarQube Scan for Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and Analyze with Maven
        run: |
          cd comp-maven
          mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.j
